### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by zkirill** [yahoo/react-intl#195]
Getting this error since upgrading to 2.0.0-beta-1.

```bash
Module not found: Error: Cannot resolve module 'react-intl'
```

```bash
Error: Cannot find module 'react-intl'
```

This is how I'm importing it.
```js
import {IntlProvider} from 'react-intl';
```

**Comment by ericf** [comment]
Can you provide a reproducible example of this issue?

**Comment by zkirill** [comment]
Is this okay?

```bash
git clone -o react-starter-kit -b master --single-branch https://github.com/kriasoft/react-starter-kit.git MyApp
$ cd MyApp
$ npm install 
$ npm install https://github.com/yahoo/react-intl.git
$ npm start

```

**Comment by ericf** [comment]
The problem is that you're installing the package from git instead of npm. The build files are created in an npm prepublish script and are not checked-in to git.

```
npm install react-intl@next
```

**Comment by zkirill** [comment]
It's working. Thank you so much, @ericf!!! :smile:
